// <auto-generated />
namespace Gym_Management_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userprofilefieldsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofilefieldsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202304240820425_userprofilefieldsadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
