// <auto-generated />
namespace Gym_Management_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class popDriverRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(popDriverRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202305280644086_popDriverRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
