// <auto-generated />
namespace Gym_Management_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class gymproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gymproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202304141925432_gymproducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
